apiVersion: v1
kind: Service
metadata:
  name: mariner
  namespace: marinertest
spec:
  type: LoadBalancer
  selector:
    app: mariner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080